<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">calidad</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">caracteriscas_red</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">caracteristicas_disco</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">caracteristicas_impresoras</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">caracteristicas_memoria</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">caracteristicas_pantalla</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">cargo</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">componentes</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">equipo</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">estados_solucion</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">problema</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">software</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">software_has_equipo</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">solucion</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">tipo_componente</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">tipo_equipo</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">tipo_impresion</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">tipo_pantalla</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">tipodisco</a>
<a class="w3-bar-item w3-button w3-hover-black" onclick="llamarAccion($(this).text())">usuario</a>
